export default {
    base: "http://www.reddit.com/",
    baseSubreddit: "http://www.reddit.com/r/",
	hot: "hot.json",
    new: "new.json",
    rising: "rising.json",
    login: "https://ssl.reddit.com/api/login",
    search: "https://api.reddit.com/api/subreddits_by_topic.json?query=",
    submit: "http://www.reddit.com/api/submit",
    appId: "3jW2zskiPBBJCg",
    oauthBase: "https://www.reddit.com/api/v1/authorize?state=reactreddit&response_type=code&scope=identity%20mysubreddits%20submit%20privatemessages%20read&client_id=3jW2zskiPBBJCg&redirect_uri=http://reactreddit/authorize&duration=permanent",
    refreshToken: "https://www.reddit.com/api/v1/access_token",
    me: "https://oauth.reddit.com/api/v1/me",
    captcha: "https://oauth.reddit.com/api/needs_captcha",
    newCaptcha: "http://www.reddit.com/api/new_captcha",
    comment: "https://oauth.reddit.com/api/comment",
    friends: "https://oauth.reddit.com/api/v1/me/friends.json",
    unfriend: "https://oauth.reddit.com/api/unfriend",
    submit: "https://oauth.reddit.com/api/submit",
    user: "https://www.reddit.com/user/",
}   